### ISSUE TITLE
Larapoll is open for developement! 

### ISSUE THREAD

**Issue by akiyamaSM** [akiyamaSM/larapoll#13]
Its been a long time since I ever contributed to the package, Now I feel that I can be able to add new thing on demande.
So Feel Free to ask for things you may want to see in the next releasse.

**Comment by vesper8** [comment]
hey man! hadn't really looked at this for a few months and super happy to see the number of commits as almost tripled since i made my fork

looking forward to seeing what you've added. I see you added the hasVoted too. I think my approach might be a bit cleaner and making use of the relationships between models. Check it out?

https://github.com/vesper8/larapoll/commits/master

I had also added a way to prevent duplicates. any chance you could add it as well? check out my commit above

I'll let you know if I have any other ideas! keep it up!

**Comment by akiyamaSM** [comment]
Great! Make a PR and I'll merge it!
